### ISSUE TITLE
Error displaying figures and tables at API Standards documentation

### ISSUE THREAD

**Issue by arshPratap** [unifyai/docs#3]
Currently in the [API Standards documentation](https://unify.ai/docs/ivy/overview/related_work/api_standards.html) , I am witnessing the following error : 
<img width="800" alt="Screenshot 2023-07-19 at 2 42 08 AM" src="https://github.com/unifyai/docs/assets/62841337/d93bd796-bb86-4599-a18b-6b1b4f7e947e">

**Comment by KareemMAX** [comment]
You should instead make an issue in https://github.com/unifyai/ivy.
